### ISSUE TITLE
Can't proceed after selecting continue 

### ISSUE THREAD

**Issue by unclesnr** [stevesec/egp_basicinstall#2]
I followed your instructions using curl -SSL https://install-evilgophish.net | bash, but I encountered an error on the third step when I select Continue, I always get the error that says: "Cancel was selected, exiting installer".

**Comment by stevesec** [comment]
Hi,

This should be fixed, please test it out and let me know. Thank you!

**Comment by stevesec** [comment]
Closing the issue as this has been tested on Debian 11.

Thank you
